version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: tennisclub-mysql
    restart: always
    environment:
      MYSQL_DATABASE: tennisclub
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: tennisclub
      MYSQL_PASSWORD: tennispassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
